[[headers]]
for = "/*"
[headers.values]
  Content-Security-Policy = """
    default-src 'self';
    frame-src https://www.youtube.com;
    script-src 'self' 'unsafe-inline' https://www.youtube.com;
    style-src 'self' 'unsafe-inline';
  """
